### PR TITLE
Fixed two iOS concurrency issues: One crash and one unrecoverable bad state.

### PR DESCRIPTION
**Pull request by GeirSmestad**
-Resolved a crash that occurs when the user closes the scanner at the same time that a QR code is detected.
-Solved blank screen error that occurs on iOS7 due to an animation concurrecy issue.

I'm reachable at geir.smestad@gmail.com if there are any questions; we would love to have these fixes included in the trunk so we don't have to maintain a separate version of the repo.

Kind regards,
Geir

### CODE REVIEW

**Comment by Redth** [comment]
Thanks, I'm going to clean this up a bit post-merge but just moving some logic into the `finally` of the try catch block instead of duplicating the calls.

**Comment by GeirSmestad** [comment]
Much appreciated :) Hope you'll get the chance to get the latest version of the trunk to the Xamarin Component Store at some point, it would be really helpful for us. Thanks for your help.

**Comment by Redth** [comment]
Yep, it's now on the component store.

**Comment by GeirSmestad** [comment]
Wonderful, many thanks :)

**Pull request merged**
