### PR TITLE
For iOS 13, setting the ModalPresentationStyle to FullScreen

### PR DESCRIPTION
**Pull request by jhonatanfernando**
It was changed the ModalPresentationStyle of ZXingScannerViewController to FullScreen mode, in iOS 13 it was showing as a popup.

### CODE REVIEW

**Comment by Manne990** [comment]
This change is really needed

**Comment by Redth** [comment]
Can you remove your changes to the csproj files and just include the .cs file change?

**Comment by jhonatanfernando** [comment]
@Redth I tried again.

**Comment by Redth** [comment]
Thanks for your contribution!  I've done a lot of work to modernize the ZXing.Net.Mobile code base and have merged those changes into master.  I've included fixes from your PR manually.  Please open a new issue or PR if you have more suggestions or changes.  Thank you so much for your help!

**Comment by giri-hp** [comment]
@Redth Is it possible to put this fix also in 2.X.X release. Unfortunately my project requires this fix and I am not in a position to upgrade this library to 3.X because of other dependencies. Thanks.

**Comment by mbugbee** [comment]
@Redth to echo @giri-hp, would it be possible to get a 2.X.X version with the fullscreen fix?  I don't feel comfortable using a beta build of 3.0 in a production app.

**Pull request closed without merging**
