### PR TITLE
[UWP] AutoFocus support

### PR DESCRIPTION
**Pull request by F1nZeR**
For now preview picture is blurred because AutoFocus by default works only on screen tap event.

- [x] Add continuous autofocus support by default
- [x] Implement focus areas logic

Other:
- [x] Add error handlers for exceptions when camera is null
- [x] Prevent screen from sleeping
- [x] Fix preview buffer and correctly handle phone rotation
- [x] Handle mirroring on front camera
- [x] Handle external camera

### CODE REVIEW

**Comment by Redth** [comment]
This is looking great so far!

**Comment by F1nZeR** [comment]
@Redth there are some commits which are not related to this PR, so should I split it into different PRs?

Last two commits helps 25a50a4 to finally fix UWP scanning problems.

**Comment by Redth** [comment]
No need to do the extra work, same PR is fine :)

**Comment by Redth** [comment]
Thanks for all of your work, this is super helpful!

**Pull request merged**
