### PR TITLE
For iOS 13, setting the ModalPresentationStyle to FullScreen

### PR DESCRIPTION
**Pull request by jhonatanfernando**
For iOS 13, setting the ModalPresentationStyle to FullScreen

### CODE REVIEW

**Comment by nitrouscutter** [comment]
Hello, I scan page is tabbed on iOS 13 and tried to create a custom renderer on my own and couldn't seem to find a way. I saw this and its exactly what we need to go out! I was wondering when this will go out? I think currently all iOS 13 apps that use this library arent working right.

**Comment by nitrouscutter** [comment]
@Redth

**Comment by ricardomomm** [comment]
I think that the build definition is using an older SDK

**Comment by Redth** [comment]
Thanks for your contribution!  I've done a lot of work to modernize the ZXing.Net.Mobile code base and have merged those changes into master.  I've included fixes from your PR manually.  Please open a new issue or PR if you have more suggestions or changes.  Thank you so much for your help!

**Pull request closed without merging**
