### PR TITLE
Xamarin Forms Binding Support

### PR DESCRIPTION
**Pull request by dansiegel**
Updated existing Bindable Properties calling that were calling the deprecated Create method.
Added Bindings to existing properties.
Added Bindable Result Property.
Refractored event handlers.

### CODE REVIEW

**Comment by dansiegel** [comment]
looks like you have a problem with your build process on appveyor. When the script 'install-android-sdk.ps1' ran, it didn't take the echo 'y' pipe correct. Can't tell what else may have happened further along since the page has a tendency to freeze my browser.

**Comment by jasoncouture** [comment]
Had a similar (same?) issue on this pull request: https://github.com/Redth/ZXing.Net.Mobile/pull/281

Your pull seems to cover much more than mine. Can you take a look at mine and make sure you get anything in it, and i'll close mine out?

**Comment by dansiegel** [comment]
@jasoncouture it looks like my PR does in fact cover the same properties that yours does. One big difference though is that this one uses the ICommand property so that you can use a Xamarin Forms Command, or a Prism DelegateCommand.

**Comment by jasoncouture** [comment]
Yup, i'll close mine out, Thanks for taking the time to look at it!

**Comment by Redth** [comment]
Sorry for taking so long on this, thanks for the contribution and cleaning it up!

**Comment by dansiegel** [comment]
not a problem. happy to help.

**Pull request merged**
