### PR TITLE
Issues/718

### PR DESCRIPTION
**Pull request by Maxallica**
Issue
https://github.com/Redth/ZXing.Net.Mobile/issues/718

Branch
https://github.com/Maxallica/ZXing.Net.Mobile/tree/issues/718

Commit - 19. April 2019 16:23:35
Fixed issue NullReferenceException due to Context in ZXingScannerViewRenderer
Xamarin.Forms version greater than or equal 2.5 has optimized Context integration to avoid null Context
Added constructor with Context
Removed unused variable requestPermissionTask
Added condition to check if Context is an Activity
#718

Commit - 19. April 2019 16:19:42
Upgraded Xamarin.Forms version to 2.5.0.280555

Test
Integrated compiled library in our own project (Release-Build).

### CODE REVIEW

**Comment by Maxallica** [comment]
Please release a new version with this fix.

**Comment by radioactiveman** [comment]
Hi @Redth, I have seen you have merged some PRs recently. 👍 Could you please merge this one as well please? It is required to make the ZXing compatible with Xamarin.Forms > 2.5.0 (released in 2017). Do you also plan to release a new package version on NuGet?

Thank you.

**Comment by Redth** [comment]
I’m working on a new local branch right now which moves code around a lot to use multi targeting. I’ll push the branch soon but it doesn’t make sense to merge additional PRs right now given the whole project structure is changing. But don’t worry it will be using a much newer forms version.

**Comment by Redth** [comment]
Thanks for your contribution!  I've done a lot of work to modernize the ZXing.Net.Mobile code base and have merged those changes into master.  I've included fixes from your PR manually.  Please open a new issue or PR if you have more suggestions or changes.  Thank you so much for your help!

**Pull request closed without merging**
