### PR TITLE
fixed bindable IsScanning property to be settable multiple times (#496)

### PR DESCRIPTION
**Pull request by PaulVrugt**
This change fixes some open issues. One of them is #496 

The IsScanning property of the ScannerView Control is bindable, but once you switched it off an on, the scanner didn't work again, because the camera was no never re-initialized.

Furthermore, when scanning was disabled, and you left the page via a Navigation.PushAsync, the camera was setup again via a RefreshCamera call. However, this should not do anything if the camera is not initialized, because then the NonmarshalingPreviewCallback event listener was not attached again.

There is an existing pull request that has some of the changed of this pull request (#725) but this one fixes some more scenario's

edit:
I've added a commit to avoid the camera to be setup multiple times. In our app, we have a scannerview on our main page. When we disable scanning, and navigate to a different page, and open an external app via startactivityforresult, and then return to the app, the SurfaceCreated is called again. This causes the "SetupCamera" method to be called, and forces the SurfaceView into scanning mode, even when we disabled it before. The extra commit avoids this method from being called multiple times.

### CODE REVIEW

**Comment by PaulVrugt** [comment]
@Redth 
Could you give me some feedback on this? We are currently using a forked build of the component containing this fix, because otherwise we cannot properly use the scannerview component. This fix makes the component much more usable. I might be a good idea to merge this pull request and create a new release containing the latest fixes. I think it would help a lot of people.

**Comment by PaulVrugt** [comment]
@Redth 
Any way to get your attention? This pull requests fixes several issues and I would really like to have this merged. Besides this, we have some other issues I cannot seem to find the cause of. We'd like to have these issues fixed, and I'm willing to put in the work to have it fixed, however, I need your help to point me in the correct direction. We we need some sign of life from you.....

**Comment by PaulVrugt** [comment]
@Redth 
I know you are probably busy, but we're still waiting for a sign of life.....

**Comment by Redth** [comment]
Apologies, not much time to work on this project lately, but I am hoping to have some very soon.  I'll have a look at this PR shortly

**Comment by PaulVrugt** [comment]
@Redth 

Great! As soon as we get to the point that this PR is merged, I can demonstrate a different issue we are still having using an repro-project, that we can't seem to resolve. Right now, i cannot demonstrate it, because without the fixes in this PR we cannot get to the point of the issue, because the components stops working at an earlier point.

I am willing to put in the effort myself in fixing the issue and creating the PR, but I need some guidance in what direction to search for the issue, since we can't seem to figure out why it is happening. But we'll cross that bridge once we get there.

**Comment by PaulVrugt** [comment]
@Redth 

Still waiting for that review....

Meanwhile, I've added an extra fix for the issue I mentioned earlier we were unable to find. We managed to find it after all and fixed is. The issue was that on android 7, the SurfaceView wasn't removed from the activity when using the Forms version of the scannerview. This caused a scannerview on a second page not being visible because the surfaceview of the scanner of the other page was rendered on top of it. The scanning worked fine though :)

As a fix for this, the surfaceview is now hidden when scanning i stopped, and made visible again when the scanning starts again.

**Comment by PaulVrugt** [comment]
@Redth 
What does a guy have to do to get some attention? This pull request fixes loads of issues with the forms component. I know you're probably busy, but I think you'll be helping a lot of people I you spend a little time (as you stated half a year ago!) to review these changes and merge them if you agree.

**Comment by Redth** [comment]
Apologies, I really have little time to work on this these days.  I'm going to try and collect a few PR's and roll them up into a release though.  Thanks!

**Comment by PaulVrugt** [comment]
@Redth 

It's almost a year later, and there is still no new release. Is this project dead? If so, is there an alternative?

**Pull request merged**
