### PR TITLE
BUGFIX - Forms Android SurfaceView when IsScanning is set to False th…

### PR DESCRIPTION
**Pull request by tomasz23**
…e camera is disabled but never enabled when IsScanning is to True anytime after disable state

updated sample Forms to include buttons to turn off camera and then on as described in documentation by using IsScanning

### CODE REVIEW

**Comment by tomasz23** [comment]
Tested on Android 6.0 and 7.1

**Comment by knocte** [comment]
@tomasz23 this commit seems to try to address 2 issues at the same time, right? Why does it add three buttons? (these are not mentioned in the commit message so it's difficult to know what is the intended purpose of them)

**Comment by tomasz23** [comment]
This address only one issue 0 when IsScanning is switched the SurfaceView is not reinitialized after it was destroyed by setting IsScanning to false. The demo I adjusted to illustrate the problem and that the fix resolved this problem. Original sample never actually set IsScanning=False and the back to True thus it was not noticed that SurfaceView would never be regenerated.

**Comment by Redth** [comment]
Thanks for your contribution!  I've done a lot of work to modernize the ZXing.Net.Mobile code base and have merged those changes into master.  I've included fixes from your PR manually.  Please open a new issue or PR if you have more suggestions or changes.  Thank you so much for your help!

**Pull request closed without merging**
